TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DATA += devlinkam95.proto

#=======================================
include $(TOP)/configure/RULES
