TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB_INSTALLS += $(TOP)/linkam95Sup/devlinkam95.proto

#=======================================
include $(TOP)/configure/RULES
